runtime: nodejs14

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 2

env_variables:
  DB_NAME: demo
  DB_USER: postgres
  DB_PASSWORD: F/gr7OOD#FPoo?cy
  DB_PORT: 5432
  DB_HOST: /cloudsql/buoyant-notch-360016:us-central1:demo